version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  securitywebapi:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
    depends_on:
      - userdb

  learningmgmtsyswebapi:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - coursedb
    ports:
      - "8001:80"

  apigateway:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

    depends_on:
        - securitywebapi
        - learningmgmtsyswebapi
